#!/bin/bash

# E-Commerce Demo Commands - Manual Execution Guide
# Execute these commands step by step for demonstration

echo "================================================="
echo "E-COMMERCE WITH INVENTORY (ECI) DEMO COMMANDS"
echo "================================================="
echo ""

echo "SEGMENT 1: DOCKER SETUP"
echo "========================"
echo "# Clean and start all services"
echo "docker-compose down -v"
echo "docker system prune -f"
echo "DOCKER_BUILDKIT=1 docker-compose up --build -d"
echo ""
echo "# Wait 30 seconds, then check status"
echo "docker ps --format \"table {{.Names}}\\t{{.Status}}\\t{{.Ports}}\""
echo ""

echo "SEGMENT 2: HEALTH CHECKS"
echo "========================="
echo "# Check all service health endpoints"
echo "curl http://localhost:8081/v1/health  # Catalog Service"
echo "curl http://localhost:8082/v1/health  # Customer Service"
echo "curl http://localhost:8083/v1/health  # Inventory Service"
echo "curl http://localhost:8084/v1/health  # Payment Service"
echo "curl http://localhost:8085/health     # Order Service"
echo "curl http://localhost:8086/health     # Shipment Service"
echo "curl http://localhost:8087/health     # Notification Service"
echo ""

echo "SEGMENT 3: INTER-SERVICE WORKFLOW"
echo "=================================="
echo "# Run complete e-commerce workflow demonstration"
echo "python3 interservice-workflow.py"
echo ""
echo "# Or run individual API calls:"
echo "# 1. Search products"
echo "curl \"http://localhost:8081/v1/products?limit=5\""
echo ""
echo "# 2. Register customer"
echo "curl -X POST \"http://localhost:8082/v1/users/register\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"email\":\"demo@test.com\",\"full_name\":\"Demo User\",\"password\":\"pass123\"}'"
echo ""
echo "# 3. Reserve inventory"
echo "curl -X POST \"http://localhost:8083/v1/inventory/reserve\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"product_id\":1,\"quantity\":2,\"reservation_minutes\":15}'"
echo ""
echo "# 4. Process payment"
echo "curl -X POST \"http://localhost:8084/v1/payments\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"order_id\":\"demo-001\",\"amount\":199.99,\"currency\":\"USD\",\"idempotency_key\":\"demo-key-001\"}'"
echo ""

echo "SEGMENT 4: DATABASE VIEWS"
echo "=========================="
echo "# Show PostgreSQL databases"
echo "docker exec postgres_main psql -U poojasrinivasan -c \"\\l\""
echo ""
echo "# Show data from each service database"
echo "docker exec postgres_main psql -U poojasrinivasan -d catalog_db -c \"SELECT * FROM products LIMIT 5;\""
echo "docker exec postgres_main psql -U poojasrinivasan -d inventory_db -c \"SELECT * FROM inventory LIMIT 5;\""
echo "docker exec postgres_main psql -U poojasrinivasan -d customer_db -c \"SELECT customer_id, email, status FROM customers LIMIT 5;\""
echo "docker exec postgres_main psql -U poojasrinivasan -d payment_db -c \"SELECT payment_id, order_id, amount, status FROM payments LIMIT 5;\""
echo ""
echo "# Show MySQL data"
echo "docker exec mysql_db mysql -u root -prootpassword -e \"USE orders_db; SELECT * FROM orders LIMIT 5;\""
echo "docker exec mysql_db mysql -u root -prootpassword -e \"USE shipments_db; SELECT * FROM shipments LIMIT 5;\""
echo ""

echo "SEGMENT 5: KUBERNETES DEPLOYMENT"
echo "================================="
echo "# Start Minikube and deploy services"
echo "minikube start --memory=8192 --cpus=4"
echo "minikube addons enable ingress"
echo ""
echo "# Deploy to Kubernetes"
echo "cd k8s-manifests"
echo "kubectl apply -f 00-databases.yaml"
echo "kubectl apply -f 01-catalog-service.yaml"
echo "kubectl apply -f 02-customer-service.yaml"
echo "kubectl apply -f 03-inventory-service.yaml"
echo "kubectl apply -f 04-payment-service.yaml"
echo ""
echo "# Check deployment status"
echo "kubectl get pods -o wide"
echo "kubectl get svc"
echo ""
echo "# Test service connectivity"
echo "kubectl port-forward svc/catalog-service 8081:8080 &"
echo "curl http://localhost:8081/v1/health"
echo ""

echo "SEGMENT 6: MONITORING"
echo "====================="
echo "# Deploy monitoring stack"
echo "kubectl apply -f monitoring/"
echo ""
echo "# Port forward to access dashboards"
echo "kubectl port-forward -n monitoring svc/prometheus 9090:9090 &"
echo "kubectl port-forward -n monitoring svc/grafana 3000:3000 &"
echo ""
echo "# Access dashboards"
echo "# Prometheus: http://localhost:9090"
echo "# Grafana: http://localhost:3000 (admin/admin)"
echo ""

echo "================================================="
echo "DEMO COMPLETE"
echo "================================================="
echo "Key achievements demonstrated:"
echo "- 7 microservices with database-per-service architecture"
echo "- Complete inter-service communication workflows"
echo "- Docker containerization with health checks"
echo "- Kubernetes deployment and orchestration"
echo "- Monitoring with Prometheus and Grafana"
echo "- Production-ready microservices platform"
echo ""