# Customer Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: ecommerce
  labels:
    app: customer-service
    service: customer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
        service: customer
    spec:
      containers:
      - name: customer-service
        image: e-commerce-with-inventory-eci-customerservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "postgres-main"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: postgres-password
        - name: DB_NAME
          value: "customer_db"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
---
# Customer Service ClusterIP Service
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: ecommerce
  labels:
    app: customer-service
spec:
  selector:
    app: customer-service
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  type: ClusterIP
---
# Customer Service NodePort for external access
apiVersion: v1
kind: Service
metadata:
  name: customer-service-nodeport
  namespace: ecommerce
  labels:
    app: customer-service
spec:
  selector:
    app: customer-service
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30003
    name: http
  type: NodePort