# Payment Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: ecommerce
  labels:
    app: payment-service
    service: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        service: payment
    spec:
      containers:
      - name: payment-service
        image: e-commerce-with-inventory-eci-payment_service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
        env:
        - name: DB_HOST
          value: "postgres-main"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: postgres-password
        - name: DB_NAME
          value: "payment_db"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 60
          periodSeconds: 30
---
# Payment Service ClusterIP Service
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ecommerce
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - port: 8002
    targetPort: 8002
    name: http
  type: ClusterIP
---
# Payment Service NodePort for external access
apiVersion: v1
kind: Service
metadata:
  name: payment-service-nodeport
  namespace: ecommerce
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - port: 8002
    targetPort: 8002
    nodePort: 30004
    name: http
  type: NodePort